// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {system} from '../models';
import {hosts} from '../models';
import {php} from '../models';
import {config} from '../models';
import {sites} from '../models';

export function AddHostEntry(arg1:string,arg2:string):Promise<boolean>;

export function BrowseFolder(arg1:string):Promise<string>;

export function BrowseHtaccessFile():Promise<string>;

export function ChangeSitePHP(arg1:string,arg2:string):Promise<boolean>;

export function ChangeSiteRoot(arg1:string,arg2:string):Promise<boolean>;

export function CheckComposer():Promise<string>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function CheckGit():Promise<string>;

export function CheckIndexFilesExist(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<Array<string>>;

export function CheckMySQLVersion():Promise<main.VersionResult>;

export function CheckNginxVersion():Promise<main.VersionResult>;

export function CheckNodeJS():Promise<string>;

export function CheckPHPVersion():Promise<main.VersionResult>;

export function CheckPortConflicts():Promise<Array<system.PortConflict>>;

export function CheckRedisVersion():Promise<main.VersionResult>;

export function CheckWinget():Promise<boolean>;

export function ClearAppLog():Promise<boolean>;

export function ClearLog(arg1:string):Promise<boolean>;

export function ConvertHtaccess(arg1:string):Promise<string>;

export function CreateIndexFiles(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<boolean>;

export function CreateLaravelProject(arg1:string,arg2:string):Promise<boolean>;

export function CreateMySQLDatabase(arg1:string):Promise<string>;

export function CreateMySQLUser(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateSite(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function DeleteHostEntries(arg1:Array<string>):Promise<boolean>;

export function DeleteHostEntry(arg1:string):Promise<boolean>;

export function DeleteMySQLVersion(arg1:string):Promise<boolean>;

export function DeleteNginxVersion(arg1:string):Promise<boolean>;

export function DeletePHPVersion(arg1:string):Promise<boolean>;

export function DeleteRedisVersion(arg1:string):Promise<boolean>;

export function DeleteSite(arg1:string,arg2:boolean):Promise<boolean>;

export function DownloadGit(arg1:boolean):Promise<boolean>;

export function DownloadNginx(arg1:string):Promise<boolean>;

export function DownloadNodeJS(arg1:boolean):Promise<boolean>;

export function DownloadPHP(arg1:string):Promise<string>;

export function DownloadRedis(arg1:string):Promise<boolean>;

export function DownloadUpdate(arg1:string):Promise<string>;

export function DropMySQLDatabase(arg1:string):Promise<string>;

export function DropMySQLUser(arg1:string,arg2:string):Promise<string>;

export function ExecRedisCommand(arg1:string):Promise<string>;

export function ExportMySQLDatabase(arg1:string):Promise<string>;

export function FlushDNS():Promise<boolean>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetAppLog():Promise<Array<string>>;

export function GetBasePath():Promise<string>;

export function GetDefaultBasePath():Promise<string>;

export function GetHostsEntries():Promise<Array<hosts.HostEntry>>;

export function GetHostsPath():Promise<string>;

export function GetInstallLocation():Promise<string>;

export function GetInstalledBrowsers():Promise<Array<system.Browser>>;

export function GetLogs(arg1:string,arg2:number):Promise<Array<string>>;

export function GetMySQLActiveVersion():Promise<string>;

export function GetMySQLAvailableVersions():Promise<Array<string>>;

export function GetMySQLConnectionInfo():Promise<main.MySQLConnectionInfo>;

export function GetMySQLDatabases():Promise<Array<string>>;

export function GetMySQLDatabasesInfo():Promise<Array<main.MySQLDatabaseInfo>>;

export function GetMySQLInstalledVersions():Promise<Array<string>>;

export function GetMySQLUserGrants(arg1:string,arg2:string):Promise<Array<string>>;

export function GetMySQLUsers():Promise<Array<main.MySQLUserInfo>>;

export function GetNginxActiveVersion():Promise<string>;

export function GetNginxAvailableVersions():Promise<Array<string>>;

export function GetNginxInstalledVersions():Promise<Array<string>>;

export function GetPHPArchivedVersions():Promise<Array<string>>;

export function GetPHPAvailableVersions():Promise<Array<string>>;

export function GetPHPConfig(arg1:string):Promise<php.PHPConfig>;

export function GetPHPExtensions(arg1:string):Promise<Array<php.PHPExtension>>;

export function GetPHPIni(arg1:string):Promise<string>;

export function GetPHPInstalledVersions():Promise<Array<string>>;

export function GetRedisActiveVersion():Promise<string>;

export function GetRedisAvailableVersions():Promise<Array<string>>;

export function GetRedisInstalledVersions():Promise<Array<string>>;

export function GetServicesStatus():Promise<Array<system.ServiceStatus>>;

export function GetSettings():Promise<config.AppSettings>;

export function GetSiteRewrites(arg1:string):Promise<string>;

export function GetSites():Promise<Array<sites.Site>>;

export function GetSystemStats():Promise<system.SystemStats>;

export function GrantMySQLDatabase(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ImportMySQLDatabase(arg1:string):Promise<string>;

export function InstallComposer(arg1:boolean):Promise<boolean>;

export function InstallMySQL(arg1:string):Promise<string>;

export function InstallUpdate():Promise<string>;

export function IsMySQLRunning():Promise<boolean>;

export function IsNginxRunning():Promise<boolean>;

export function IsOnline():Promise<boolean>;

export function IsPHPRunning(arg1:string):Promise<boolean>;

export function IsRedisRunning():Promise<boolean>;

export function KillProcess(arg1:number):Promise<boolean>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function OpenPHPIni(arg1:string):Promise<boolean>;

export function OpenURL(arg1:string):Promise<void>;

export function ReloadNginx():Promise<boolean>;

export function RestartMySQL():Promise<boolean>;

export function RestartNginx():Promise<string>;

export function RestartRedis():Promise<boolean>;

export function RevokeMySQLDatabase(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RunArtisan(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RunLaravelUpdate(arg1:string,arg2:string):Promise<void>;

export function SavePHPConfig(arg1:string,arg2:php.PHPConfig):Promise<boolean>;

export function SavePHPExtensions(arg1:string,arg2:Array<string>):Promise<boolean>;

export function SavePHPIni(arg1:string,arg2:string):Promise<boolean>;

export function SaveSettings(arg1:config.AppSettings):Promise<boolean>;

export function SaveSiteRewrites(arg1:string,arg2:string):Promise<boolean>;

export function SetMySQLActiveVersion(arg1:string):Promise<boolean>;

export function SetMySQLUserPassword(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetNginxActiveVersion(arg1:string):Promise<boolean>;

export function SetRedisActiveVersion(arg1:string):Promise<boolean>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function StartMySQL():Promise<boolean>;

export function StartNginx():Promise<string>;

export function StartPHP(arg1:string):Promise<boolean>;

export function StartRedis():Promise<boolean>;

export function StopAllServices():Promise<void>;

export function StopMySQL():Promise<boolean>;

export function StopNginx():Promise<boolean>;

export function StopPHP(arg1:string):Promise<boolean>;

export function StopRedis():Promise<boolean>;

export function ToggleHostEntry(arg1:string):Promise<boolean>;

export function ToggleSite(arg1:string):Promise<boolean>;
