// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHostEntry(arg1, arg2) {
  return window['go']['main']['App']['AddHostEntry'](arg1, arg2);
}

export function BrowseFolder() {
  return window['go']['main']['App']['BrowseFolder']();
}

export function BrowseHtaccessFile() {
  return window['go']['main']['App']['BrowseHtaccessFile']();
}

export function ChangeSitePHP(arg1, arg2) {
  return window['go']['main']['App']['ChangeSitePHP'](arg1, arg2);
}

export function CheckComposer() {
  return window['go']['main']['App']['CheckComposer']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CheckGit() {
  return window['go']['main']['App']['CheckGit']();
}

export function CheckMySQLVersion() {
  return window['go']['main']['App']['CheckMySQLVersion']();
}

export function CheckNginxVersion() {
  return window['go']['main']['App']['CheckNginxVersion']();
}

export function CheckNodeJS() {
  return window['go']['main']['App']['CheckNodeJS']();
}

export function CheckPHPVersion() {
  return window['go']['main']['App']['CheckPHPVersion']();
}

export function CheckPortConflicts() {
  return window['go']['main']['App']['CheckPortConflicts']();
}

export function CheckRedisVersion() {
  return window['go']['main']['App']['CheckRedisVersion']();
}

export function CheckWinget() {
  return window['go']['main']['App']['CheckWinget']();
}

export function ClearAppLog() {
  return window['go']['main']['App']['ClearAppLog']();
}

export function ClearLog(arg1) {
  return window['go']['main']['App']['ClearLog'](arg1);
}

export function ConvertHtaccess(arg1) {
  return window['go']['main']['App']['ConvertHtaccess'](arg1);
}

export function CreateIndexFiles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateIndexFiles'](arg1, arg2, arg3, arg4);
}

export function CreateLaravelProject(arg1, arg2) {
  return window['go']['main']['App']['CreateLaravelProject'](arg1, arg2);
}

export function CreateMySQLDatabase(arg1) {
  return window['go']['main']['App']['CreateMySQLDatabase'](arg1);
}

export function CreateMySQLUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateMySQLUser'](arg1, arg2, arg3);
}

export function CreateSite(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateSite'](arg1, arg2, arg3, arg4);
}

export function DeleteHostEntries(arg1) {
  return window['go']['main']['App']['DeleteHostEntries'](arg1);
}

export function DeleteHostEntry(arg1) {
  return window['go']['main']['App']['DeleteHostEntry'](arg1);
}

export function DeleteMySQLVersion(arg1) {
  return window['go']['main']['App']['DeleteMySQLVersion'](arg1);
}

export function DeleteNginxVersion(arg1) {
  return window['go']['main']['App']['DeleteNginxVersion'](arg1);
}

export function DeletePHPVersion(arg1) {
  return window['go']['main']['App']['DeletePHPVersion'](arg1);
}

export function DeleteRedisVersion(arg1) {
  return window['go']['main']['App']['DeleteRedisVersion'](arg1);
}

export function DeleteSite(arg1, arg2) {
  return window['go']['main']['App']['DeleteSite'](arg1, arg2);
}

export function DownloadGit(arg1) {
  return window['go']['main']['App']['DownloadGit'](arg1);
}

export function DownloadNginx(arg1) {
  return window['go']['main']['App']['DownloadNginx'](arg1);
}

export function DownloadNodeJS(arg1) {
  return window['go']['main']['App']['DownloadNodeJS'](arg1);
}

export function DownloadPHP(arg1) {
  return window['go']['main']['App']['DownloadPHP'](arg1);
}

export function DownloadRedis(arg1) {
  return window['go']['main']['App']['DownloadRedis'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function DropMySQLDatabase(arg1) {
  return window['go']['main']['App']['DropMySQLDatabase'](arg1);
}

export function DropMySQLUser(arg1, arg2) {
  return window['go']['main']['App']['DropMySQLUser'](arg1, arg2);
}

export function ExecRedisCommand(arg1) {
  return window['go']['main']['App']['ExecRedisCommand'](arg1);
}

export function ExportMySQLDatabase(arg1) {
  return window['go']['main']['App']['ExportMySQLDatabase'](arg1);
}

export function FlushDNS() {
  return window['go']['main']['App']['FlushDNS']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetAppLog() {
  return window['go']['main']['App']['GetAppLog']();
}

export function GetBasePath() {
  return window['go']['main']['App']['GetBasePath']();
}

export function GetDefaultBasePath() {
  return window['go']['main']['App']['GetDefaultBasePath']();
}

export function GetHostsEntries() {
  return window['go']['main']['App']['GetHostsEntries']();
}

export function GetInstalledBrowsers() {
  return window['go']['main']['App']['GetInstalledBrowsers']();
}

export function GetLogs(arg1, arg2) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2);
}

export function GetMySQLActiveVersion() {
  return window['go']['main']['App']['GetMySQLActiveVersion']();
}

export function GetMySQLAvailableVersions() {
  return window['go']['main']['App']['GetMySQLAvailableVersions']();
}

export function GetMySQLConnectionInfo() {
  return window['go']['main']['App']['GetMySQLConnectionInfo']();
}

export function GetMySQLDatabases() {
  return window['go']['main']['App']['GetMySQLDatabases']();
}

export function GetMySQLDatabasesInfo() {
  return window['go']['main']['App']['GetMySQLDatabasesInfo']();
}

export function GetMySQLInstalledVersions() {
  return window['go']['main']['App']['GetMySQLInstalledVersions']();
}

export function GetMySQLUserGrants(arg1, arg2) {
  return window['go']['main']['App']['GetMySQLUserGrants'](arg1, arg2);
}

export function GetMySQLUsers() {
  return window['go']['main']['App']['GetMySQLUsers']();
}

export function GetNginxActiveVersion() {
  return window['go']['main']['App']['GetNginxActiveVersion']();
}

export function GetNginxAvailableVersions() {
  return window['go']['main']['App']['GetNginxAvailableVersions']();
}

export function GetNginxInstalledVersions() {
  return window['go']['main']['App']['GetNginxInstalledVersions']();
}

export function GetPHPArchivedVersions() {
  return window['go']['main']['App']['GetPHPArchivedVersions']();
}

export function GetPHPAvailableVersions() {
  return window['go']['main']['App']['GetPHPAvailableVersions']();
}

export function GetPHPConfig(arg1) {
  return window['go']['main']['App']['GetPHPConfig'](arg1);
}

export function GetPHPExtensions(arg1) {
  return window['go']['main']['App']['GetPHPExtensions'](arg1);
}

export function GetPHPIni(arg1) {
  return window['go']['main']['App']['GetPHPIni'](arg1);
}

export function GetPHPInstalledVersions() {
  return window['go']['main']['App']['GetPHPInstalledVersions']();
}

export function GetRedisActiveVersion() {
  return window['go']['main']['App']['GetRedisActiveVersion']();
}

export function GetRedisAvailableVersions() {
  return window['go']['main']['App']['GetRedisAvailableVersions']();
}

export function GetRedisInstalledVersions() {
  return window['go']['main']['App']['GetRedisInstalledVersions']();
}

export function GetServicesStatus() {
  return window['go']['main']['App']['GetServicesStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSiteRewrites(arg1) {
  return window['go']['main']['App']['GetSiteRewrites'](arg1);
}

export function GetSites() {
  return window['go']['main']['App']['GetSites']();
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function GrantMySQLDatabase(arg1, arg2, arg3) {
  return window['go']['main']['App']['GrantMySQLDatabase'](arg1, arg2, arg3);
}

export function ImportMySQLDatabase(arg1) {
  return window['go']['main']['App']['ImportMySQLDatabase'](arg1);
}

export function InstallComposer(arg1) {
  return window['go']['main']['App']['InstallComposer'](arg1);
}

export function InstallMySQL(arg1) {
  return window['go']['main']['App']['InstallMySQL'](arg1);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function IsMySQLRunning() {
  return window['go']['main']['App']['IsMySQLRunning']();
}

export function IsNginxRunning() {
  return window['go']['main']['App']['IsNginxRunning']();
}

export function IsOnline() {
  return window['go']['main']['App']['IsOnline']();
}

export function IsPHPRunning(arg1) {
  return window['go']['main']['App']['IsPHPRunning'](arg1);
}

export function IsRedisRunning() {
  return window['go']['main']['App']['IsRedisRunning']();
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function OpenPHPIni(arg1) {
  return window['go']['main']['App']['OpenPHPIni'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ReloadNginx() {
  return window['go']['main']['App']['ReloadNginx']();
}

export function RestartMySQL() {
  return window['go']['main']['App']['RestartMySQL']();
}

export function RestartNginx() {
  return window['go']['main']['App']['RestartNginx']();
}

export function RestartRedis() {
  return window['go']['main']['App']['RestartRedis']();
}

export function RevokeMySQLDatabase(arg1, arg2, arg3) {
  return window['go']['main']['App']['RevokeMySQLDatabase'](arg1, arg2, arg3);
}

export function RunArtisan(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunArtisan'](arg1, arg2, arg3);
}

export function RunLaravelUpdate(arg1, arg2) {
  return window['go']['main']['App']['RunLaravelUpdate'](arg1, arg2);
}

export function SavePHPConfig(arg1, arg2) {
  return window['go']['main']['App']['SavePHPConfig'](arg1, arg2);
}

export function SavePHPExtensions(arg1, arg2) {
  return window['go']['main']['App']['SavePHPExtensions'](arg1, arg2);
}

export function SavePHPIni(arg1, arg2) {
  return window['go']['main']['App']['SavePHPIni'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveSiteRewrites(arg1, arg2) {
  return window['go']['main']['App']['SaveSiteRewrites'](arg1, arg2);
}

export function SetMySQLActiveVersion(arg1) {
  return window['go']['main']['App']['SetMySQLActiveVersion'](arg1);
}

export function SetMySQLUserPassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetMySQLUserPassword'](arg1, arg2, arg3);
}

export function SetNginxActiveVersion(arg1) {
  return window['go']['main']['App']['SetNginxActiveVersion'](arg1);
}

export function SetRedisActiveVersion(arg1) {
  return window['go']['main']['App']['SetRedisActiveVersion'](arg1);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function StartMySQL() {
  return window['go']['main']['App']['StartMySQL']();
}

export function StartNginx() {
  return window['go']['main']['App']['StartNginx']();
}

export function StartPHP(arg1) {
  return window['go']['main']['App']['StartPHP'](arg1);
}

export function StartRedis() {
  return window['go']['main']['App']['StartRedis']();
}

export function StopAllServices() {
  return window['go']['main']['App']['StopAllServices']();
}

export function StopMySQL() {
  return window['go']['main']['App']['StopMySQL']();
}

export function StopNginx() {
  return window['go']['main']['App']['StopNginx']();
}

export function StopPHP(arg1) {
  return window['go']['main']['App']['StopPHP'](arg1);
}

export function StopRedis() {
  return window['go']['main']['App']['StopRedis']();
}

export function ToggleHostEntry(arg1) {
  return window['go']['main']['App']['ToggleHostEntry'](arg1);
}

export function ToggleSite(arg1) {
  return window['go']['main']['App']['ToggleSite'](arg1);
}
